global:
  scrape_interval: 5s  # How often to scrape targets by default

scrape_configs:
  - job_name: "user-records-service"
    static_configs:
      - targets: ["api:8000"]  # FastAPI metrics endpoint
